In [1]:
import torch

In [2]:
# 2.1.8 T1
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X > Y, X < Y

(tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [3]:
# 2.1.8 T2
a = torch.arange(3).reshape((3,1,1))
b = torch.arange(2).reshape((1,2,1))
a, b

(tensor([[[0]],
 
         [[1]],
 
         [[2]]]),
 tensor([[[0],
          [1]]]))

In [4]:
a + b

tensor([[[0],
         [1]],

        [[1],
         [2]],

        [[2],
         [3]]])