In [1]:
import torch
x = torch.arange(12, dtype=torch.int8).reshape(3, 4)
y = torch.arange(start=-6, end=6, dtype=torch.int8).reshape(3, 4)

In [3]:
# 2.3.13 T1
x.T.T == x

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [4]:
# 2.3.13.T2
print(x.T + y.T)
print((x+y).T)
print(x.T+y.T==(x+y).T)

tensor([[-6,  2, 10],
        [-4,  4, 12],
        [-2,  6, 14],
        [ 0,  8, 16]], dtype=torch.int8)
tensor([[-6,  2, 10],
        [-4,  4, 12],
        [-2,  6, 14],
        [ 0,  8, 16]], dtype=torch.int8)
tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])


In [5]:
# 2.3.13 T3
X = torch.arange(24).reshape(2, 3, 4)
print(len(X))

2


In [8]:
# 2.3.13 T3
# wrong code
try:
    print(X/X.sum(axis=1))
except RuntimeError as e:
    print(e)
# after debug
print(X/X.sum(axis=1, keepdim=True))

The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1
tensor([[[0.0000, 0.0667, 0.1111, 0.1429],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.6667, 0.6000, 0.5556, 0.5238]],

        [[0.2500, 0.2549, 0.2593, 0.2632],
         [0.3333, 0.3333, 0.3333, 0.3333],
         [0.4167, 0.4118, 0.4074, 0.4035]]])


In [7]:
# 2.3.13 T3
print(X.sum(axis=0).shape)
print(X.sum(axis=1).shape)
print(X.sum(axis=2).shape)

torch.Size([3, 4])
torch.Size([2, 4])
torch.Size([2, 3])


In [15]:
# 2.3.13 T3
# 返回X展平成1维之后2-范数
torch.linalg.norm(X.float())

tensor(65.7571)